### PR TITLE
Modified templates/triton.py. Added logs & additional arguments.

### PR DESCRIPTION
**Pull request by vishalsrao**
- Additional arguments: E.g. num-heads for distilBERT, parameters to be included in config.pbtxt of tokenizer & model directories
- Modified templates/triton.py to generate configs using protocol buffer (tritonclient.grpc.model_config_pb2)
- Added logs
- Minor refactoring

### CODE REVIEW

**Comment by pommedeterresautee** [comment]
Hi @vishalsrao, thank you for the PR!

Would it be possible to refactor it in several smaller ones?
In particular we use HTTP communication in our company and can't drop it for protobuf, it has to be optional, etc.

**Comment by vishalsrao** [comment]
Protocol buffer has been used in templates/triton.py only for generating configs' texts using a more programmatic approach instead of generating them using formatted strings. I dont think this should impact the use of HTTP protocol for invoking Triton models. Let me know if you feel there could be any issues due to this.

**Comment by pommedeterresautee** [comment]
I may have misunderstood the code.
FWIW, I am fixing distilbert support in #42

**Comment by pommedeterresautee** [comment]
I read more carefully the code and now better understand the intent.
What the json files to provide on command line are supposed to contain?

**Comment by vishalsrao** [comment]
Model's metadata can be stored in parameters object of the config file. tokenizer-meta-json and model-meta-json can be used to store any useful info of tokenizer and model. Information from both these json files are added to inference model's parameters. 

E.g., I often use these parameters to store info of label names in multi-label/class use cases. These parameters can be read by the API invoking Triton using:
```
model_configs_dict = triton_client.get_model_config(model_nm, as_json=True)['config']
model_configs_dict['parameters']
```

**Pull request closed without merging**
