### PR TITLE
WIP - Support Token Classification

### PR DESCRIPTION
**Pull request by sam-writer**
I think this makes it so TD can handle TokenClassification.

However, the model I picked to test with seems to not convert well, both the ONNX and TensorRT conversion fail on the `assert np.areclose`, and I am not sure what this means...

I am testing it with

`$ python src/transformer_deploy/convert.py -m dslim/bert-large-NER  --backend onnx --seq-len 8 128 256 --batch-size 1 1 1 --task=TokenClassification --verbose`

Also, sorry for all the commits, I can squash them on my fork and make it clean later, I just wanted to know if you had any idea why this was failing.

### CODE REVIEW

**Comment by sam-writer** [comment]
@pommedeterresautee Not sure if you have time to look at this at all, but here is the status:

1. The model I picked to test, `dslim/bert-large-NER` happens to fail the asserts which check for tensor `allclose` after conversion to ONNX/TRT. I think this is a coincidence
2. the generated Triton config files get the shape wrong

my plan is to ignore 1 and figure out 2 today 😅

**Comment by sam-writer** [comment]
Updates: 1 really was a fluke. Switching the model to `MODEL=dslim/bert-base-NER-uncased` fixed it. Can it only handle BERT-base right now? I think I got 2 fixed though, so TokenClassificaiton config files work.

**Comment by pommedeterresautee** [comment]
@sam-writer accuracy check need to be reworked. Basically, there are always differences between backends, FP16 can increase them (because of overflows), and large models have a tendency to be a bit unstable. 

The issues with the way accuracy check is done:
- input is random, if you are not lucky, it will find some (impossible IRL) values that will overflow FP16 operators -> bad accuracy
- there is a single check for a single input, no fallback strategy

The easiest way to mitigate this behavior is to:
- execute several accuracy checks, 
- compute the absolute value of the diff btw Pytorch output and other framework output, 
- average, 
- check if it's under the threshold.

The example in the README is a large model, I have already tested several large ones. If you want, you can "disable" the check by fixing a large tolerance (--atol 10).

**Comment by sam-writer** [comment]
Closing this as I don't think I will get to it and it is very out of date at this point.

**Comment by v1nc3nt27** [comment]
@sam-writer I'm also interested in making this work for token classification. I'll probably work on this soon, so could you perhaps shortly let me know what the open todos were or at which point you got stuck? Thanks!

**Comment by sam-writer** [comment]
@v1nc3nt27 the changes to `convert.py` should be minimal, something like

```python
    if args.task == "TokenClassification":
        from transformers import AutoModelForTokenClassification
        model_pytorch: PreTrainedModel = AutoModelForTokenClassification.from_pretrained(
            args.model, use_auth_token=auth_token
        )
        logging.info(f"task: TokenClassification")
    else:
        model_pytorch: PreTrainedModel = AutoModelForSequenceClassification.from_pretrained(
            args.model, use_auth_token=auth_token
        )
        logging.info(f"task: SequenceClassification")
```

then you need to make some changes to the Triton templating, either by making a new file or somehow chaning https://github.com/ELS-RD/transformer-deploy/blob/main/src/transformer_deploy/triton/configuration.py

**Comment by sam-writer** [comment]
when you have it working will you open a PR? :D

**Comment by v1nc3nt27** [comment]
I encountered several problems after the quantization itself (seemed to) go well. Plus, I pretty much have the same problem as you with working on an older state of the project. Anyhow, if I get it working, I'll either update my version of the project or implement it for the current one :).

**Pull request closed without merging**
